import sqlite3


def get_category_aldi():
    array = [
        "https://shop.aldi.hu/kinalat/tejtermek-tojas/tej",
        "https://shop.aldi.hu/kinalat/tejtermek-tojas/sajt",
        "https://shop.aldi.hu/kinalat/tejtermek-tojas/tejfol",
        "https://shop.aldi.hu/kinalat/tejtermek-tojas/kefir",
        "https://shop.aldi.hu/kinalat/tejtermek-tojas/joghurt",
        "https://shop.aldi.hu/kinalat/tejtermek-tojas/turo",
        "https://shop.aldi.hu/kinalat/tejtermek-tojas/tejszin",
        "https://shop.aldi.hu/kinalat/tejtermek-tojas/desszert",
        "https://shop.aldi.hu/kinalat/tejtermek-tojas/vaj-sajtkrem",
        "https://shop.aldi.hu/kinalat/tejtermek-tojas/tojas",
        "https://shop.aldi.hu/kinalat/tejtermek-tojas/margarin",
        "https://shop.aldi.hu/kinalat/pekaru/kenyer",
        "https://shop.aldi.hu/kinalat/pekaru/zsemle-kifli",
        "https://shop.aldi.hu/kinalat/pekaru/sutemeny",
        "https://shop.aldi.hu/kinalat/pekaru/sos-pekaru",
        "https://shop.aldi.hu/kinalat/pekaru/tartos-aru",
        "https://shop.aldi.hu/kinalat/pekaru/edes-pekaru",
        "https://shop.aldi.hu/kinalat/pekaru/kalacs",
        "https://shop.aldi.hu/kinalat/pekaru/tortilla",
        "https://shop.aldi.hu/kinalat/zoldseg-gyumolcs/gyumolcs",
        "https://shop.aldi.hu/kinalat/zoldseg-gyumolcs/aszalt-gyumolcs",
        "https://shop.aldi.hu/kinalat/zoldseg-gyumolcs/zoldseg",
        "https://shop.aldi.hu/kinalat/zoldseg-gyumolcs/magvak",
        "https://shop.aldi.hu/kinalat/zoldseg-gyumolcs/salatak",
        "https://shop.aldi.hu/kinalat/zoldseg-gyumolcs/fuszernovenyek",
        "https://shop.aldi.hu/kinalat/alkoholos-italok/feher-bor",
        "https://shop.aldi.hu/kinalat/alkoholos-italok/rose-bor",
        "https://shop.aldi.hu/kinalat/alkoholos-italok/voros-bor",
        "https://shop.aldi.hu/kinalat/alkoholos-italok/sor-koktel-gyumolcsbor",
        "https://shop.aldi.hu/kinalat/alkoholos-italok/tomeny",
        "https://shop.aldi.hu/kinalat/alkoholos-italok/pezsgoes-habzo-bor",
        "https://shop.aldi.hu/kinalat/alkoholos-italok/likor",
        "https://shop.aldi.hu/kinalat/alkoholos-italok/egyeb-alkoholos-italok",
        "https://shop.aldi.hu/kinalat/fagyasztott-elelmiszer/zoldsegek-gyumolcsok",
        "https://shop.aldi.hu/kinalat/fagyasztott-elelmiszer/hus",
        "https://shop.aldi.hu/kinalat/fagyasztott-elelmiszer/hal",
        "https://shop.aldi.hu/kinalat/fagyasztott-elelmiszer/pizzak-sos-sutemenyek",
        "https://shop.aldi.hu/kinalat/fagyasztott-elelmiszer/keszetelek",
        "https://shop.aldi.hu/kinalat/fagyasztott-elelmiszer/jegkremek-desszertek",
        "https://shop.aldi.hu/kinalat/fagyasztott-elelmiszer/jegkocka",
        "https://shop.aldi.hu/kinalat/haztartasi--es-vegyiaru-papiraru/mososzerek",
        "https://shop.aldi.hu/kinalat/haztartasi--es-vegyiaru-papiraru/mosogatoszer",
        "https://shop.aldi.hu/kinalat/haztartasi--es-vegyiaru-papiraru/tisztitoszer",
        "https://shop.aldi.hu/kinalat/haztartasi--es-vegyiaru-papiraru/takaritoeszkoz",
        "https://shop.aldi.hu/kinalat/haztartasi--es-vegyiaru-papiraru/haztartasi-csomagolok",
        "https://shop.aldi.hu/kinalat/haztartasi--es-vegyiaru-papiraru/szemeteszsak",
        "https://shop.aldi.hu/kinalat/haztartasi--es-vegyiaru-papiraru/legfrissitok",
        "https://shop.aldi.hu/kinalat/haztartasi--es-vegyiaru-papiraru/rovarirto-es-novenyirto-szerek",
        "https://shop.aldi.hu/kinalat/haztartasi--es-vegyiaru-papiraru/haztartasi-papiraru",
        "https://shop.aldi.hu/kinalat/haztartasi--es-vegyiaru-papiraru/egyeb-haztartasi-cikkek-",
        "https://shop.aldi.hu/kinalat/allateledel-es-felszereles/kutyaeledel",
        "https://shop.aldi.hu/kinalat/allateledel-es-felszereles/macskaeledel",
        "https://shop.aldi.hu/kinalat/allateledel-es-felszereles/egyeb-allatok-eledelei",
        "https://shop.aldi.hu/kinalat/allateledel-es-felszereles/felszereles",
        "https://shop.aldi.hu/kinalat/alapveto-elelmiszerek/cukor-es-edesitoszerek",
        "https://shop.aldi.hu/kinalat/alapveto-elelmiszerek/liszt-dara-panirmorzsa",
        "https://shop.aldi.hu/kinalat/alapveto-elelmiszerek/koretek-tesztak",
        "https://shop.aldi.hu/kinalat/alapveto-elelmiszerek/olaj-es-ecet",
        "https://shop.aldi.hu/kinalat/alapveto-elelmiszerek/konzervek",
        "https://shop.aldi.hu/kinalat/alapveto-elelmiszerek/lekvar-mez-krem",
        "https://shop.aldi.hu/kinalat/alapveto-elelmiszerek/instant-etelek",
        "https://shop.aldi.hu/kinalat/alapveto-elelmiszerek/etelizesites",
        "https://shop.aldi.hu/kinalat/alapveto-elelmiszerek/szoszok-martasok",
        "https://shop.aldi.hu/kinalat/alapveto-elelmiszerek/kavek-teak-italporok",
        "https://shop.aldi.hu/kinalat/alapveto-elelmiszerek/keszetelek4",
        "https://shop.aldi.hu/kinalat/alapveto-elelmiszerek/reggelizo-pehely-muzli",
        "https://shop.aldi.hu/kinalat/alapveto-elelmiszerek/sutes-fozes",
        "https://shop.aldi.hu/kinalat/baba/babaetel-ital",
        "https://shop.aldi.hu/kinalat/baba/babaapolas",
        "https://shop.aldi.hu/kinalat/szepseg-egeszseg/furdes-kezmosas",
        "https://shop.aldi.hu/kinalat/szepseg-egeszseg/hajapolas",
        "https://shop.aldi.hu/kinalat/szepseg-egeszseg/szajapolas",
        "https://shop.aldi.hu/kinalat/szepseg-egeszseg/testapolas",
        "https://shop.aldi.hu/kinalat/szepseg-egeszseg/noi-higienia",
        "https://shop.aldi.hu/kinalat/szepseg-egeszseg/ferfi-higienia",
        "https://shop.aldi.hu/kinalat/szepseg-egeszseg/egyeb-cikkek",
        "https://shop.aldi.hu/kinalat/szepseg-egeszseg/vitaminok-kiegeszitok",
        "https://shop.aldi.hu/kinalat/szepseg-egeszseg/parfumok",
        "https://shop.aldi.hu/kinalat/italok/szensavas-uditoitalok",
        "https://shop.aldi.hu/kinalat/italok/szensavmentes-uditoitalok",
        "https://shop.aldi.hu/kinalat/italok/szensavas-asvanyviz",
        "https://shop.aldi.hu/kinalat/italok/szensavmentes-asvanyviz",
        "https://shop.aldi.hu/kinalat/italok/izesitett-vizek",
        "https://shop.aldi.hu/kinalat/italok/gyumolcslevek",
        "https://shop.aldi.hu/kinalat/italok/szorp-italpor-citromle",
        "https://shop.aldi.hu/kinalat/italok/energia-sport-gyogyitalok",
        "https://shop.aldi.hu/kinalat/hus-hal-felvagott/felvagottak",
        "https://shop.aldi.hu/kinalat/hus-hal-felvagott/csomagolt-es-pultos-husok",
        "https://shop.aldi.hu/kinalat/hus-hal-felvagott/halak",
        "https://shop.aldi.hu/kinalat/hus-hal-felvagott/husok-es-szalonnak",
        "https://shop.aldi.hu/kinalat/nassolnivalok/tablas-csokolade",
        "https://shop.aldi.hu/kinalat/nassolnivalok/keksz-napolyi-piskota",
        "https://shop.aldi.hu/kinalat/nassolnivalok/szeletes-termek",
        "https://shop.aldi.hu/kinalat/nassolnivalok/cukorkak-ragogumi",
        "https://shop.aldi.hu/kinalat/nassolnivalok/puffasztott-snack",
        "https://shop.aldi.hu/kinalat/nassolnivalok/sos-ragcsalnivalo",
        "https://shop.aldi.hu/aldi/kinalat/kozepso-sor",
        "https://shop.aldi.hu/kinalat/az-ev-sajat-markas-termeke",
        "https://shop.aldi.hu/aldi/kinalat/grill-es-kert",
    ]
    return array


def get_category_auchan():
    array = [
        ("https://online.auchan.hu/shop/elelmiszer/tejtermek-tojas-sajt/tejek-tejitalok-novenyi-italok.c-6537", "Tejek, tejitalok, növényi italok"),
        ("https://online.auchan.hu/shop/elelmiszer/tejtermek-tojas-sajt/csomagolt-sajtok.c-5680", "Csomagolt sajtok"),
        ("https://online.auchan.hu/shop/elelmiszer/tejtermek-tojas-sajt/tejfol-kefir-finomfol.c-5675", "Tejföl, kefir, finomföl"),
        ("https://online.auchan.hu/shop/elelmiszer/tejtermek-tojas-sajt/joghurtok.c-5669", "Joghurtok"),
        ("https://online.auchan.hu/shop/elelmiszer/tejtermek-tojas-sajt/turo-tejszin.c-5677", "Túró, tejszín"),
        ("https://online.auchan.hu/shop/elelmiszer/tejtermek-tojas-sajt/tojas.c-5676", "Tojás"),
        ("https://online.auchan.hu/shop/elelmiszer/tejtermek-tojas-sajt/tejdesszertek.c-5674", "Tejdesszertek"),
        ("https://online.auchan.hu/shop/elelmiszer/tejtermek-tojas-sajt/vaj-vajkrem-es-margarin.c-5678","Vaj, vajkrém és margarin"),
        ("https://online.auchan.hu/shop/elelmiszer/tejtermek-tojas-sajt/alternativ-novenyi-termekek.c-13938", "Alternatív, növényi termékek"),
        ("https://online.auchan.hu/shop/elelmiszer/hus-felvagott-hal-kenyelmi-etelek/csomagolt-huskeszitmenyek.c-5623", "Csomagolt húskészítmények"),
        ("https://online.auchan.hu/shop/elelmiszer/hus-felvagott-hal-kenyelmi-etelek/csomagolt-husfelek.c-6606", "Csomagolt húsfélék"),
        ("https://online.auchan.hu/shop/elelmiszer/hus-felvagott-hal-kenyelmi-etelek/csomagolt-friss-halak.c-10275", "Csomagolt friss halak"),
        ("https://online.auchan.hu/shop/elelmiszer/hus-felvagott-hal-kenyelmi-etelek/halkeszitmenyek.c-6696", "Halkészítmények"),
        ("https://online.auchan.hu/shop/elelmiszer/hus-felvagott-hal-kenyelmi-etelek/kenyelmi-etelek-hidegkonyha.c-5562", "Kényelmi ételek, hidegkonyha"),
        ("https://online.auchan.hu/shop/elelmiszer/zoldseg-gyumolcs/bio.c-11425", "BIO"),
        ("https://online.auchan.hu/shop/elelmiszer/zoldseg-gyumolcs/gyumolcs.c-5681", "Gyümölcs"),
        ("https://online.auchan.hu/shop/elelmiszer/zoldseg-gyumolcs/zoldseg.c-5685", "Zöldség"),
        ("https://online.auchan.hu/shop/elelmiszer/zoldseg-gyumolcs/aszalvanyok.c-5684", "Aszalványok"),
        ("https://online.auchan.hu/shop/elelmiszer/zoldseg-gyumolcs/elorecsomagolt-salata.c-5682", "Előrecsomagolt saláta"),
        ("https://online.auchan.hu/shop/elelmiszer/zoldseg-gyumolcs/fuszernoveny.c-6552", "Fűszernövény"),
        ("https://online.auchan.hu/shop/elelmiszer/zoldseg-gyumolcs/szaritott-sutes-fozes-alapanyag.c-6560", "Szárított sütés főzés alapanyag"),
        ("https://online.auchan.hu/shop/elelmiszer/pekaruk-kenyerek-cukraszat/fagyasztott-pekaru.c-14251", "Fagyasztott Pékáru"),
        ("https://online.auchan.hu/shop/elelmiszer/pekaruk-kenyerek-cukraszat/kenyer.c-5652", "Kenyér"),
        ("https://online.auchan.hu/shop/elelmiszer/pekaruk-kenyerek-cukraszat/kalacsfelek.c-7033", "Kalácsfélék"),
        ("https://online.auchan.hu/shop/elelmiszer/pekaruk-kenyerek-cukraszat/friss-pekaru.c-6510", "Friss pékáru"),
        ("https://online.auchan.hu/shop/elelmiszer/pekaruk-kenyerek-cukraszat/elosutott-pekaru.c-10196", "Elősütött pékáru"),
        ("https://online.auchan.hu/shop/elelmiszer/pekaruk-kenyerek-cukraszat/zsemle-kifli-szendvicsalapok.c-5654", "Zsemle, Kifli, Szendvicsalapok"),
        ("https://online.auchan.hu/shop/elelmiszer/pekaruk-kenyerek-cukraszat/tartos-sutemeny.c-5653", "Tartós sütemény"),
        ("https://online.auchan.hu/shop/elelmiszer/pekaruk-kenyerek-cukraszat/nemzetkozi-tartos-pekaru.c-7035", "Nemzetközi tartós pékáru"),
        ("https://online.auchan.hu/shop/elelmiszer/pekaruk-kenyerek-cukraszat/cukraszat.c-9057", "Cukrászat"),
        ("https://online.auchan.hu/shop/elelmiszer/pekaruk-kenyerek-cukraszat/extrudalt-puffasztott-termekek.c-7036", "Extrudált, puffasztott termékek"),
        ("https://online.auchan.hu/shop/elelmiszer/tartos-elelmiszerek/rizs-teszta-reformkoret.c-5569", "Rizs, tészta, reformköret"),
        ("https://online.auchan.hu/shop/elelmiszer/tartos-elelmiszerek/olaj-ecet.c-6612", "Olaj, ecet"),
        ("https://online.auchan.hu/shop/elelmiszer/tartos-elelmiszerek/liszt-cukor-panirmorzsa.c-6613", "Liszt, cukor, panírmorzsa"),
        ("https://online.auchan.hu/shop/elelmiszer/tartos-elelmiszerek/muzli-gabonapehely.c-5567", "Müzli, gabonapehely"),
        ("https://online.auchan.hu/shop/elelmiszer/tartos-elelmiszerek/mez-lekvar-es-mogyorokrem.c-5566", "Méz, lekvár és mogyorókrém"),
        ("https://online.auchan.hu/shop/elelmiszer/tartos-elelmiszerek/konzervek-savanyusagok.c-5565", "Konzervek, savanyúságok"),
        ("https://online.auchan.hu/shop/elelmiszer/tartos-elelmiszerek/sutes-fozes-hozzavalok.c-5570", "Sütés főzés hozzávalók"),
        ("https://online.auchan.hu/shop/elelmiszer/tartos-elelmiszerek/etelizesites-fuszerek.c-5561", "Ételízesítés, fűszerek"),
        ("https://online.auchan.hu/shop/elelmiszer/tartos-elelmiszerek/szoszok-martasok.c-5571", "Szószok, mártások"),
        ("https://online.auchan.hu/shop/elelmiszer/tartos-elelmiszerek/nemzetkozi-konyha.c-5568", "Nemzetközi konyha"),
        ("https://online.auchan.hu/shop/elelmiszer/tartos-elelmiszerek/instant-etelalapok-es-levespor.c-5563", "Instant ételalapok és levespor"),
        ("https://online.auchan.hu/shop/elelmiszer/tartos-elelmiszerek/huvelyes-termenyek.c-14091", "Hüvelyes termények"),
        ("https://online.auchan.hu/shop/elelmiszer/edesseg-csokolade-nasi/chips.c-5577", "Chips"),
        ("https://online.auchan.hu/shop/elelmiszer/edesseg-csokolade-nasi/sos-sutemeny.c-5586", "Sós sütemény"),
        ("https://online.auchan.hu/shop/elelmiszer/edesseg-csokolade-nasi/magvak.c-5582", "Magvak"),
        ("https://online.auchan.hu/shop/elelmiszer/edesseg-csokolade-nasi/tablas-csokolade.c-5588", "Táblás csokoládé"),
        ("https://online.auchan.hu/shop/elelmiszer/edesseg-csokolade-nasi/keksz-napolyi-piskota.c-5589", "Keksz, nápolyi, piskóta"),
        ("https://online.auchan.hu/shop/elelmiszer/edesseg-csokolade-nasi/szeletes-termek.c-5587", "Szeletes termék"),
        ("https://online.auchan.hu/shop/elelmiszer/edesseg-csokolade-nasi/desszert.c-5579", "Desszert"),
        ("https://online.auchan.hu/shop/elelmiszer/edesseg-csokolade-nasi/cukorka.c-5578", "Cukorka"),
        ("https://online.auchan.hu/shop/elelmiszer/edesseg-csokolade-nasi/ragogumi.c-5585", "Rágógumi"),
        ("https://online.auchan.hu/shop/elelmiszer/edesseg-csokolade-nasi/puffasztott-snack.c-5584", "Puffasztott snack"),
        ("https://online.auchan.hu/shop/elelmiszer/edesseg-csokolade-nasi/pattogatott-kukorica.c-5583", "Pattogatott kukorica"),
        ("https://online.auchan.hu/shop/elelmiszer/edesseg-csokolade-nasi/croissant.c-9099", "Croissant"),
        ("https://online.auchan.hu/shop/elelmiszer/edesseg-csokolade-nasi/ajandekkosar.c-13779", "Ajándékkosár"),
        ("https://online.auchan.hu/shop/elelmiszer/fagyasztott-elelmiszer/fagyasztott-grill-termekek.c-13795", "Fagyasztott grill termékek"),
        ("https://online.auchan.hu/shop/elelmiszer/fagyasztott-elelmiszer/jegkrem.c-5608", "Jégkrém"),
        ("https://online.auchan.hu/shop/elelmiszer/fagyasztott-elelmiszer/fagyasztott-keszetel-pizza.c-5606", "Fagyasztott készétel, Pizza"),
        ("https://online.auchan.hu/shop/elelmiszer/fagyasztott-elelmiszer/fagyasztott-burgonya.c-5598", "Fagyasztott burgonya"),
        ("https://online.auchan.hu/shop/elelmiszer/fagyasztott-elelmiszer/fagyasztott-desszert.c-5600", "Fagyasztott desszert"),
        ("https://online.auchan.hu/shop/elelmiszer/fagyasztott-elelmiszer/fagyasztott-zoldseg-gyumolcs-sajt.c-5599", "Fagyasztott zöldség, gyümölcs, sajt"),
        ("https://online.auchan.hu/shop/elelmiszer/fagyasztott-elelmiszer/fagyasztott-hal.c-5604", "Fagyasztott hal"),
        ("https://online.auchan.hu/shop/elelmiszer/fagyasztott-elelmiszer/fagyasztott-baromfi.c-5602", "Fagyasztott baromfi"),
        ("https://online.auchan.hu/shop/elelmiszer/fagyasztott-elelmiszer/fagyasztott-hus.c-6642", "Fagyasztott hús"),
        ("https://online.auchan.hu/shop/elelmiszer/fagyasztott-elelmiszer/jegkocka.c-6457", "Jégkocka"),
        ("https://online.auchan.hu/shop/elelmiszer/bor-es-egyeb-alkoholos-italok/feher-borok.c-6485", "Fehér borok"),
        ("https://online.auchan.hu/shop/elelmiszer/bor-es-egyeb-alkoholos-italok/rose-borok.c-6487", "Rosé borok"),
        ("https://online.auchan.hu/shop/elelmiszer/bor-es-egyeb-alkoholos-italok/voros-borok.c-6486", "Vörös borok"),
        ("https://online.auchan.hu/shop/elelmiszer/bor-es-egyeb-alkoholos-italok/habzo-borok.c-6496", "Habzó borok"),
        ("https://online.auchan.hu/shop/elelmiszer/bor-es-egyeb-alkoholos-italok/gyumolcsborok.c-6629", "Gyümölcsborok"),
        ("https://online.auchan.hu/shop/elelmiszer/bor-es-egyeb-alkoholos-italok/pezsgok.c-6628", "Pezsgők"),
        ("https://online.auchan.hu/shop/elelmiszer/bor-es-egyeb-alkoholos-italok/szeszes-italok.c-5646", "Szeszes italok"),
        ("https://online.auchan.hu/shop/elelmiszer/bor-es-egyeb-alkoholos-italok/sorok-cider.c-5644", "Sörök, cider"),
        ("https://online.auchan.hu/shop/elelmiszer/bor-es-egyeb-alkoholos-italok/francia-borok-pezsgok.c-7145", "Francia borok, pezsgők"),
        ("https://online.auchan.hu/shop/elelmiszer/italok-kakao-tea-kave/viz.c-5636", "Víz"),
        ("https://online.auchan.hu/shop/elelmiszer/italok-kakao-tea-kave/gyumolcs-es-zoldseglevek.c-5639", "Gyümölcs és zöldséglevek"),
        ("https://online.auchan.hu/shop/elelmiszer/italok-kakao-tea-kave/szensavas-uditok.c-5645", "Szénsavas üdítők"),
        ("https://online.auchan.hu/shop/elelmiszer/italok-kakao-tea-kave/szorp.c-5647", "Szörp"),
        ("https://online.auchan.hu/shop/elelmiszer/italok-kakao-tea-kave/kis-kiszerelesu-gyumolcslevek.c-5575", "Kis kiszerelésű gyümölcslevek"),
        ("https://online.auchan.hu/shop/elelmiszer/italok-kakao-tea-kave/energia-italok.c-5638", "Energia italok"),
        ("https://online.auchan.hu/shop/elelmiszer/italok-kakao-tea-kave/limonade-es-ice-tea.c-5642", "Limonádé és ice tea"),
        ("https://online.auchan.hu/shop/elelmiszer/italok-kakao-tea-kave/auchan-meleg-italok.c-14010", "Auchan meleg italok"),
        ("https://online.auchan.hu/shop/elelmiszer/italok-kakao-tea-kave/kave-es-kaveizesito.c-5641", "Kávé és kávéízesítő"),
        ("https://online.auchan.hu/shop/elelmiszer/italok-kakao-tea-kave/kave-es-kaveizesito.c-5641", "Kávé és kávéízesítő"),
        ("https://online.auchan.hu/shop/elelmiszer/italok-kakao-tea-kave/tea.c-5648", "Tea"),
        ("https://online.auchan.hu/shop/elelmiszer/italok-kakao-tea-kave/kakao-es-italporok.c-5640", "Kakaó és italporok"),
        ("https://online.auchan.hu/shop/elelmiszer/grill-vilag/grill-elelmiszer-termekek.c-6607", "Grill élelmiszer termékek")
    ]
    return array


def get_category_penny():
    array = [
        "https://www.roksh.com/penny-hu/kinalat/tejtermek-tojas/tej",
        "https://www.roksh.com/penny-hu/kinalat/tejtermek-tojas/sajt",
        "https://www.roksh.com/penny-hu/kinalat/tejtermek-tojas/tejfol",
        "https://www.roksh.com/penny-hu/kinalat/tejtermek-tojas/kefir",
        "https://www.roksh.com/penny-hu/kinalat/tejtermek-tojas/joghurt",
        "https://www.roksh.com/penny-hu/kinalat/tejtermek-tojas/turo",
        "https://www.roksh.com/penny-hu/kinalat/tejtermek-tojas/tejszin",
        "https://www.roksh.com/penny-hu/kinalat/tejtermek-tojas/desszert",
        "https://www.roksh.com/penny-hu/kinalat/tejtermek-tojas/vaj-sajtkrem",
        "https://www.roksh.com/penny-hu/kinalat/tejtermek-tojas/margarin",
        "https://www.roksh.com/penny-hu/kinalat/pekaru/kenyer",
        "https://www.roksh.com/penny-hu/kinalat/pekaru/zsemle-kifli",
        "https://www.roksh.com/penny-hu/kinalat/pekaru/sutemeny",
        "https://www.roksh.com/penny-hu/kinalat/pekaru/sos-pekaru",
        "https://www.roksh.com/penny-hu/kinalat/pekaru/tartos-aru",
        "https://www.roksh.com/penny-hu/kinalat/pekaru/edes-pekaru",
        "https://www.roksh.com/penny-hu/kinalat/zoldseg-gyumolcs/gyumolcs",
        "https://www.roksh.com/penny-hu/kinalat/zoldseg-gyumolcs/aszalt-gyumolcs",
        "https://www.roksh.com/penny-hu/kinalat/zoldseg-gyumolcs/zoldseg",
        "https://www.roksh.com/penny-hu/kinalat/zoldseg-gyumolcs/salatak",
        "https://www.roksh.com/penny-hu/kinalat/alkoholos-italok/feher-bor",
        "https://www.roksh.com/penny-hu/kinalat/alkoholos-italok/rose-bor",
        "https://www.roksh.com/penny-hu/kinalat/alkoholos-italok/voros-bor",
        "https://www.roksh.com/penny-hu/kinalat/alkoholos-italok/sor-koktel-gyumolcsbor",
        "https://www.roksh.com/penny-hu/kinalat/alkoholos-italok/tomeny",
        "https://www.roksh.com/penny-hu/kinalat/alkoholos-italok/pezsgoes-habzo-bor",
        "https://www.roksh.com/penny-hu/kinalat/alkoholos-italok/likor",
        "https://www.roksh.com/penny-hu/kinalat/alkoholos-italok/egyeb-alkoholos-italok",
        "https://www.roksh.com/penny-hu/kinalat/haztartasi--es-vegyiaru-papiraru/mososzerek",
        "https://www.roksh.com/penny-hu/kinalat/haztartasi--es-vegyiaru-papiraru/mosogatoszer",
        "https://www.roksh.com/penny-hu/kinalat/haztartasi--es-vegyiaru-papiraru/tisztitoszer",
        "https://www.roksh.com/penny-hu/kinalat/haztartasi--es-vegyiaru-papiraru/takaritoeszkoz",
        "https://www.roksh.com/penny-hu/kinalat/haztartasi--es-vegyiaru-papiraru/haztartasi-csomagolok",
        "https://www.roksh.com/penny-hu/kinalat/haztartasi--es-vegyiaru-papiraru/szemeteszsak",
        "https://www.roksh.com/penny-hu/kinalat/haztartasi--es-vegyiaru-papiraru/legfrissitok",
        "https://www.roksh.com/penny-hu/kinalat/haztartasi--es-vegyiaru-papiraru/haztartasi-papiraru",
        "https://www.roksh.com/penny-hu/kinalat/haztartasi--es-vegyiaru-papiraru/egyeb-haztartasi-cikkek-",
        "https://www.roksh.com/penny-hu/kinalat/allateledel-es-felszereles/kutyaeledel",
        "https://www.roksh.com/penny-hu/kinalat/allateledel-es-felszereles/macskaeledel",
        "https://www.roksh.com/penny-hu/kinalat/allateledel-es-felszereles/egyeb-allatok-eledelei",
        "https://www.roksh.com/penny-hu/kinalat/alapveto-elelmiszerek/cukor-es-edesitoszerek",
        "https://www.roksh.com/penny-hu/kinalat/alapveto-elelmiszerek/liszt-dara-panirmorzsa",
        "https://www.roksh.com/penny-hu/kinalat/alapveto-elelmiszerek/koretek-tesztak",
        "https://www.roksh.com/penny-hu/kinalat/alapveto-elelmiszerek/olaj-es-ecet",
        "https://www.roksh.com/penny-hu/kinalat/alapveto-elelmiszerek/konzervek",
        "https://www.roksh.com/penny-hu/kinalat/alapveto-elelmiszerek/lekvar-mez-krem",
        "https://www.roksh.com/penny-hu/kinalat/alapveto-elelmiszerek/instant-etelek",
        "https://www.roksh.com/penny-hu/kinalat/alapveto-elelmiszerek/etelizesites",
        "https://www.roksh.com/penny-hu/kinalat/alapveto-elelmiszerek/szoszok-martasok",
        "https://www.roksh.com/penny-hu/kinalat/alapveto-elelmiszerek/kavek-teak-italporok",
        "https://www.roksh.com/penny-hu/kinalat/alapveto-elelmiszerek/keszetelek4",
        "https://www.roksh.com/penny-hu/kinalat/alapveto-elelmiszerek/reggelizo-pehely-muzli",
        "https://www.roksh.com/penny-hu/kinalat/alapveto-elelmiszerek/sutes-fozes",
        "https://www.roksh.com/penny-hu/kinalat/baba/babaetel-ital",
        "https://www.roksh.com/penny-hu/kinalat/baba/babaapolas",
        "https://www.roksh.com/penny-hu/kinalat/szepseg-egeszseg/furdes-kezmosas",
        "https://www.roksh.com/penny-hu/kinalat/szepseg-egeszseg/hajapolas",
        "https://www.roksh.com/penny-hu/kinalat/szepseg-egeszseg/szajapolas",
        "https://www.roksh.com/penny-hu/kinalat/szepseg-egeszseg/testapolas",
        "https://www.roksh.com/penny-hu/kinalat/szepseg-egeszseg/noi-higienia",
        "https://www.roksh.com/penny-hu/kinalat/szepseg-egeszseg/ferfi-higienia",
        "https://www.roksh.com/penny-hu/kinalat/szepseg-egeszseg/egyeb-cikkek",
        "https://www.roksh.com/penny-hu/kinalat/szepseg-egeszseg/vitaminok-kiegeszitok",
        "https://www.roksh.com/penny-hu/kinalat/italok/szensavas-uditoitalok",
        "https://www.roksh.com/penny-hu/kinalat/italok/szensavas-asvanyviz",
        "https://www.roksh.com/penny-hu/kinalat/italok/szensavmentes-asvanyviz",
        "https://www.roksh.com/penny-hu/kinalat/italok/gyumolcslevek",
        "https://www.roksh.com/penny-hu/kinalat/italok/szorp-italpor-citromle",
        "https://www.roksh.com/penny-hu/kinalat/italok/energia-sport-gyogyitalok",
        "https://www.roksh.com/penny-hu/kinalat/hus-hal-felvagott/felvagottak",
        "https://www.roksh.com/penny-hu/kinalat/hus-hal-felvagott/csomagolt-es-pultos-husok",
        "https://www.roksh.com/penny-hu/kinalat/nassolnivalok/tablas-csokolade",
        "https://www.roksh.com/penny-hu/kinalat/nassolnivalok/keksz-napolyi-piskota",
        "https://www.roksh.com/penny-hu/kinalat/nassolnivalok/szeletes-termek",
        "https://www.roksh.com/penny-hu/kinalat/nassolnivalok/cukorkak-ragogumi",
        "https://www.roksh.com/penny-hu/kinalat/nassolnivalok/puffasztott-snack",
        "https://www.roksh.com/penny-hu/kinalat/nassolnivalok/sos-ragcsalnivalo",
        "https://www.roksh.com/penny-hu/kinalat/fagyasztott-elelmiszer/zoldsegek-gyumolcsok",
        "https://www.roksh.com/penny-hu/kinalat/fagyasztott-elelmiszer/pizzak-sos-sutemenyek",
        "https://www.roksh.com/penny-hu/kinalat/fagyasztott-elelmiszer/keszetelek",
        "https://www.roksh.com/penny-hu/kinalat/fagyasztott-elelmiszer/jegkremek-desszertek",
        "https://www.roksh.com/penny-hu/kinalat/minden-ami-nem-elelmiszer"
    ]
    return array


def get_category_tesco():
    array = [
        'https://bevasarlas.tesco.hu/groceries/hu-HU/shop/bbq/all?include-children=true',
        'https://bevasarlas.tesco.hu/groceries/hu-HU/shop/zoldseg-gyumolcs/all?include-children=true',
        'https://bevasarlas.tesco.hu/groceries/hu-HU/shop/tejtermekek-tojas/all?include-children=true',
        'https://bevasarlas.tesco.hu/groceries/hu-HU/shop/pekaru/all?include-children=true',
        'https://bevasarlas.tesco.hu/groceries/hu-HU/shop/hus-hal-felvagott/all?include-children=true',
        'https://bevasarlas.tesco.hu/groceries/hu-HU/shop/alapveto-elelmiszerek/all?include-children=true',
        'https://bevasarlas.tesco.hu/groceries/hu-HU/shop/specialis-es-egeszseges-taplalkozas/all?include-children=true',
        'https://bevasarlas.tesco.hu/groceries/hu-HU/shop/fagyasztott-elelmiszerek/all?include-children=true',
        'https://bevasarlas.tesco.hu/groceries/hu-HU/shop/italok/all?include-children=true',
        'https://bevasarlas.tesco.hu/groceries/hu-HU/shop/alkohol/all?include-children=true',
        'https://bevasarlas.tesco.hu/groceries/hu-HU/shop/haztartas/all?include-children=true',
        'https://bevasarlas.tesco.hu/groceries/hu-HU/shop/szepsegapolas/all?include-children=true',
        'https://bevasarlas.tesco.hu/groceries/hu-HU/shop/babaapolas/all?include-children=true',
        'https://bevasarlas.tesco.hu/groceries/hu-HU/shop/kisallat/all?include-children=true',
        'https://bevasarlas.tesco.hu/groceries/hu-HU/shop/otthon-hobbi/all?include-children=true',
        'https://bevasarlas.tesco.hu/groceries/hu-HU/shop/ruhazat/all?include-children=true'
    ]
    return array


def create_database(name):
    conn = sqlite3.connect(f'databases/adatbazis_{name}.db')
    c = conn.cursor()

    c.execute('''
        CREATE TABLE IF NOT EXISTS products (
            sku TEXT PRIMARY KEY,
            category TEXT,
            image TEXT,
            name TEXT
        )
    ''')

    c.execute('''
        CREATE TABLE IF NOT EXISTS prices (
            date INTEGER DEFAULT (strftime('%s', 'now')),
            normal_price INTEGER,
            discount_price INTEGER,
            product_sku TEXT,
            FOREIGN KEY (product_sku) REFERENCES products(sku)
        )
    ''')
    conn.commit()
    conn.close()


create_database("penny")